name: Generate AI Files
on:
  # Triggers when client-data.csv changes
  push:
    paths: ['client-data.csv']
  
  # Weekly automatic update (Mondays 8AM)
  schedule:
    - cron: '0 8 * * 1'
  
  # Manual run button
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Process files
        run: python generate_ai_files.py
      
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet || (git commit -m "Auto-update [skip ci]" && git push)
